### ISSUE TITLE
Better error message for missing allocationinstrumenter agent jar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/caliper#201]
```

Jan 17, 2013 11:49:38 AM com.google.caliper.config.LoggingConfigLoader 
loadLoggingConfig
INFO: Using logging configuration at /home/user1/.caliper/logging.properties
Experiment selection: 
  Instruments:   [AllocationInstrument, MicrobenchmarkInstrument]
  User parameters:   {arguments=[1, 2, 3, 4, 5, 6], strategy=[VARARGS, EXPANSION]}
  Virtual machines:  [default]
  Selection type:    Full cartesian product

This selection yields 24 experiments.
Measuring 1 trials each of 24 experiments. Estimated runtime: 2.9m.
java.lang.IllegalStateException: Can't find required allocationinstrumenter 
agent jar
    at com.google.caliper.runner.AllocationInstrument.getExtraCommandLineArgs(AllocationInstrument.java:84)
    at com.google.caliper.runner.ExperimentingCaliperRun.createWorkerProcessBuilder(ExperimentingCaliperRun.java:270)
    at com.google.caliper.runner.ExperimentingCaliperRun.measure(ExperimentingCaliperRun.java:297)
    at com.google.caliper.runner.ExperimentingCaliperRun.run(ExperimentingCaliperRun.java:209)
    at com.google.caliper.runner.CaliperMain.exitlessMain(CaliperMain.java:107)
    at com.google.caliper.runner.CaliperMain.main(CaliperMain.java:70)
    at com.google.caliper.runner.CaliperMain.main(CaliperMain.java:59)
    at com.google.caliper.Runner.main(Runner.java:445)
    at examples.VarargsBenchmark.main(VarargsBenchmark.java:238)

An unexpected exception has been thrown by the caliper runner.
Please see https://sites.google.com/site/caliperusers/issues

```

Original issue reported on code.google.com by `Andrei.Pozolotin` on 17 Jan 2013 at 5:51

**Comment by nglorioso** [comment]
Looks like the exception message was updated: https://github.com/google/caliper/blob/7eb907479c54e5580b202ee3f590c0ba3426cfbd/caliper/src/main/java/com/google/caliper/runner/instrument/AllocationInstrument.java#L195
