### ISSUE TITLE
Unit test failure in LoggingConfigLoaderTest

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/caliper#256]
```
What steps will reproduce the problem?
1.  Invoke mvn build command ("mvn eclipse:configure-workspace eclipse:eclipse 
install")

What is the expected output? What do you see instead?

Build failed with unit test error.  See below.

What version of the product are you using? On what operating system?

- Checked out caliper from git, version b2d26bca
- Windows 7

Please provide any additional information below.

Failure stack trace follows.  If this succeeds on other OSes and fails on 
Windows, then it might be as simple as Windows not liking the file path:
- Really long filename?
- I see a mix of mostly backslashes but one forward slash?
- Colon character?  Windows uses colon characters in drive spec (i.e.: "C:").  

-------------------------------------------------------------------------------
Test set: com.google.caliper.config.LoggingConfigLoaderTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.115 sec <<< 
FAILURE!
testLoadDefaultLogConfiguration(com.google.caliper.config.LoggingConfigLoaderTes
t)  Time elapsed: 0.085 sec  <<< ERROR!
java.io.IOException: Couldn't get lock for 
C:\Users\jnewsham\AppData\Local\Temp\junit9008764239605548164\junit7777412845156
407772\log/2013-05-24T04:20:47.203Z.b69ed4fd-18f5-47fd-b9f8-ae77105c6709.log
    at java.util.logging.FileHandler.openFiles(FileHandler.java:389)
    at java.util.logging.FileHandler.<init>(FileHandler.java:254)
    at com.google.caliper.config.LoggingConfigLoader.maybeLoadDefaultLogConfiguration(LoggingConfigLoader.java:86)
    at com.google.caliper.config.LoggingConfigLoaderTest.testLoadDefaultLogConfiguration(LoggingConfigLoaderTest.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
    at org.junit.rules.RunRules.evaluate(RunRules.java:18)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
    at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)

```

Original issue reported on code.google.com by `jim.news...@gmail.com` on 24 May 2013 at 8:19

**Comment by netdpb** [comment]
This was fixed in 985408dfdafe360fd8861d95fe27282afd27ede8.
