### ISSUE TITLE
Worker exited without producing data, IllegalAccessError when trying to run the worker process manually

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/caliper#275]
```
C:\jdk\bin\java -Didea.launcher.port=7532 "-Didea.launcher.bin.path=C:\Program 
Files (x86)\JetBrains\IntelliJ IDEA 12.1.4\bin" -Dfile.encoding=UTF-8 
-classpath 
"C:\jdk\jre\lib\alt-rt.jar;C:\jdk\jre\lib\alt-string.jar;C:\jdk\jre\lib\charsets
.jar;C:\jdk\jre\lib\deploy.jar;C:\jdk\jre\lib\javaws.jar;C:\jdk\jre\lib\jce.jar;
C:\jdk\jre\lib\jsse.jar;C:\jdk\jre\lib\management-agent.jar;C:\jdk\jre\lib\plugi
n.jar;C:\jdk\jre\lib\resources.jar;C:\jdk\jre\lib\rt.jar;C:\jdk\jre\lib\ext\dnsn
s.jar;C:\jdk\jre\lib\ext\localedata.jar;C:\jdk\jre\lib\ext\sunjce_provider.jar;D
:\dev\alm\integers\build\classes\generated;D:\dev\alm\integers\lib\annotations.j
ar;D:\dev\alm\integers\lib\junit.jar;D:\dev\alm\integers\lib\caliper-1.0-beta-SN
APSHOT-all.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 
12.1.4\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain 
com.google.caliper.runner.CaliperMain com.almworks.integers.DlsBenchmark 
--verbose

Experiment selection:
  Instruments:   [allocation, runtime]
  User parameters:   {addSize=[100, 1000, 10000, 100000, 1000000]}
  Virtual machines:  [default]
  Selection type:    Full cartesian product

This selection yields 20 experiments.
<Output from dry run>
Starting experiment 1 of 20: {instrument=allocation, benchmarkMethod=dlsRemove, 
vm=default, parameters={addSize=100}}à The worker exited without producing 
data. It has likely crashed. Run with --verbose to see output.


I've inserted println statements in the beginning my @BeforeExperiment and 
@Benchmark methods, I marked them here as <Output from dry run>. 

I checked the command line for the child (worker) process and tried to run it 
manually in the command line, then I get this exception:
Exception in thread "main" java.lang.IllegalAccessError: tried to access class 
com.google.inject.multibindings.Multibinder$RealMultibinder from class 
com.google.inject.multibindings.Multibinder$RealMultibinder$$FastClassByGuice$$9
4efefc8
        at com.google.inject.multibindings.Multibinder$RealMultibinder$$FastClassByGuice$$94efefc8.invoke(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastMethod.invoke(FastMethod.java:53)
        at com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:56)
        at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:90)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
        at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:75)
        at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:73)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:73)
        at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:147)
        at com.google.inject.internal.Initializer.injectAll(Initializer.java:92)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:173)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:83)
        at com.google.caliper.worker.WorkerMain.main(WorkerMain.java:38)

Full command line for the worker process:

C:\jdk\jre\bin\java 
-javaagent:C:\Users\igor\.IntelliJIdea12\system\groovyHotSwap\gragent.jar 
-Dfile.encoding=UTF-8 -Xmx3g -Xms3g -cp 
"C:\jdk\jre\lib\ext\dnsns.jar;C:\jdk\jre\lib\ext\localedata.jar;C:\jdk\jre\lib\e
xt\sunjce_provider.jar;C:\jdk\jre\lib\alt-rt.jar;C:\jdk\jre\lib\alt-string.jar;C
:\jdk\jre\lib\charsets.jar;C:\jdk\jre\lib\deploy.jar;C:\jdk\jre\lib\javaws.jar;C
:\jdk\jre\lib\jce.jar;C:\jdk\jre
\lib\jsse.jar;C:\jdk\jre\lib\management-agent.jar;C:\jdk\jre\lib\plugin.jar;C:\j
dk\jre\lib\resources.jar;C:\jdk\jre\lib\rt.jar;D:\dev\alm\integers\build\classes
\generated;D:\dev\alm\integers\lib\annotations.jar
;D:\dev\alm\integers\lib\junit.jar;D:\dev\alm\integers\lib\caliper-1.0-beta-SNAP
SHOT-all.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 
12.1.4\lib\idea_rt.jar;C:\Users\igor\.IntelliJIdea12\system\groovyHotSwap\gragen
t.jar" -Xbatch -XX:CICompilerCount=1 -XX:+UseParallelGC 
-Dsun.reflect.inflationThreshold=0 
-javaagent:D:\dev\alm\integers\lib\caliper-1.0-beta-SNAPSHOT-all.jar 
-Xbootclasspath/a:D:\dev\alm\integers\lib\caliper-1.0-beta-SNAPSHOT-all.jar 
-XX:+PrintFlagsFinal -XX:+PrintCompilation -XX:+PrintGC 
com.google.caliper.worker.WorkerMain 
{"workerClassName":"com.google.caliper.worker.MacrobenchmarkAllocationWorker","w
orkerOptions":{"trackAllocations":"true"},"benchmarkSpec":{"className":"com.almw
orks.integers.DlsBenchmark","methodName":"dlsRemove","parameters":{"addSize":"10
0"}},"methodParameterClassNames":[],"port":57244}

OS: Win 7; JVM: 
java version "1.6.0_34"
Java(TM) SE Runtime Environment (build 1.6.0_34-b04)
Java HotSpot(TM) 64-Bit Server VM (build 20.9-b04, mixed mode)
```

Original issue reported on code.google.com by `ios...@gmail.com` on 10 Sep 2013 at 9:34

**Comment by netdpb** [comment]
This is likely obsolete now that Caliper doesn't use Guice.

**Comment by bitemyapp** [comment]
@netdpb is it? I'm getting this error with Caliper 1.0-beta-2:

```
WARNING: All illegal access operations will be denied in a future release
java.lang.IllegalAccessError: class com.google.caliper.options.OptionsModule$$FastClassByGuice$$1832ae86 tried to access method 'com.google.caliper.options.CaliperOptions com.google.caliper.options.OptionsModule.provideOptions()' (com.google.caliper.options.OptionsModule$$FastClassByGuice$$1832ae86 is in unnamed module of loader 'app'; com.google.caliper.options.OptionsModule is in unnamed module of loader 'bootstrap')
	at com.google.caliper.options.OptionsModule$$FastClassByGuice$$1832ae86.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:272)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:172)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at com.google.caliper.runner.CaliperMain.exitlessMain(CaliperMain.java:117)
	at com.google.caliper.runner.CaliperMain.main(CaliperMain.java:81)
	at com.google.caliper.runner.CaliperMain.main(CaliperMain.java:69)
	at com.bitemyapp.Main.main(Main.java:9)

An unexpected exception has been thrown by the caliper runner.
Please see https://sites.google.com/site/caliperusers/issues
make: *** [Makefile:5: run] Error 1
```

Here's my `build.gradle.kts`:

```
plugins {
    java
    application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.google.caliper:caliper:1.0-beta-2")
    implementation("com.google.code.java-allocation-instrumenter:java-allocation-instrumenter:3.1.0")
    implementation("com.google.guava:guava:18.0-jre")
    implementation("com.google.inject:guice:4.0")
}

configurations.all {
    resolutionStrategy.eachDependency {
    if (this.requested.group == "com.google.guava" && this.requested.name == "guava") {
      // Force guava 18.0, caliper:1.0-beta-2 requires it
      this.useVersion("18.0")
    }
  }
}

application {
    mainClassName = "com.bitemyapp.Main" 
}

val fatJar = task("fatJar", type = Jar::class) {
    archiveBaseName.set("${project.name}-fat")

    manifest {
        attributes["Implementation-Title"] = "Gradle Jar File Example"
        attributes["Implementation-Version"] = "0.0.1"
        attributes["Main-Class"] = "com.mkyong.DateUtils"
    }
    from(configurations.runtimeClasspath.get().map({ if (it.isDirectory) it else zipTree(it) }))
    with(tasks.jar.get() as CopySpec)
}

tasks {
    "build" {
        dependsOn(fatJar)
    }
}

tasks.withType(Jar::class) {
    manifest {
        // attributes["Manifest-Version"] = "1.0"
        attributes["Main-Class"] = "com.bitemyapp.Main"
        attributes["Premain-Class"] = "com.google.monitoring.runtime.instrumentation.AllocationInstrumenter"
        attributes["Can-Redefine-Classes"] = true
        attributes["Can-Retransform-Classes"] = true
    }
}
```

If I don't add guice to my dependencies, it complains.

**Comment by bitemyapp** [comment]
Looks like 1.0-beta-2 is from 2015 on Maven Central. Am I supposed to getting this from somewhere else?

What I'm really looking for is an equivalent to Haskell or Rust's Criterion but for Java. If there's a more widely used library for that purpose please let me know.

**Comment by cgdecker** [comment]
I'm not familiar with Criterion, but you may want to take a look at [JMH](https://openjdk.java.net/projects/code-tools/jmh/). Caliper is currently not actively being developed; there's newer code than the 1.0-beta-2 at head from work that was done last year, but we haven't made an open source release with that and it would require some additional work to get it to that point.

**Comment by bitemyapp** [comment]
@cgdecker thanks for the heads up. I'll try to get JMH working.
