### ISSUE TITLE
Method not found: org.apache.commons.math.stat.descriptive.rank.Percentile.setData

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/caliper#290]
```
What steps will reproduce the problem?
1. This very simple benchmark:

public class ArrayDigestBench {
    double[] data = new double[10000];

    @Param({"16", "32"})
    int pageSize;

    @BeforeExperiment
    protected void setUp() throws Exception {
        Random random = new Random();
        for (int i = 0; i < data.length; i++) {
            data[i] = random.nextDouble();
        }
    }

    @Benchmark
    double timeArrayDigest(int reps) {
        double r = 0;
        TDigest ad = new ArrayDigest(pageSize, 100);
        for (int i = 0; i < reps; i++) {
            for (double x : data) {
                ad.add(x);
            }
            System.out.printf("%d\n", i);
            r += ad.quantile(0.999);
        }
        System.out.printf("returning\n");
        return r;
    }
}

2. mvn compile
3. mvn exec:java -Dexec.mainClass="com.google.caliper.runner.CaliperMain" 
-Dexec.args="com.tdunning.math.stats.ArrayDigestBench"

What is the expected output? What do you see instead?

I would expect the normal caliper sort of output.

What version of the product are you using? On what operating system?

OSX version 10.9.2, 16GB RAM

java version "1.7.0_11"
Java(TM) SE Runtime Environment (build 1.7.0_11-b21)
Java HotSpot(TM) 64-Bit Server VM (build 23.6-b04, mixed mode)

  <dependency>
            <groupId>com.google.caliper</groupId>
            <artifactId>caliper</artifactId>
            <version>1.0-beta-SNAPSHOT</version>
   </dependency>

Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 
05:51:28-0800)


Please provide any additional information below

java.lang.NoSuchMethodError: 
org.apache.commons.math.stat.descriptive.rank.Percentile.setData([D)V
    at com.google.caliper.runner.ConsoleResultProcessor.processTrial(ConsoleResultProcessor.java:86)
    at com.google.caliper.runner.ExperimentingCaliperRun.run(ExperimentingCaliperRun.java:154)
    at com.google.caliper.runner.CaliperMain.exitlessMain(CaliperMain.java:140)
    at com.google.caliper.runner.CaliperMain.main(CaliperMain.java:79)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
    at java.lang.Thread.run(Thread.java:722)

```

Original issue reported on code.google.com by `ted.dunn...@gmail.com` on 4 Mar 2014 at 1:11

**Comment by netdpb** [comment]
Closing for now. Please reopen if this error reoccurs with the latest release.
