### ISSUE TITLE
CaliperMain throws an Exception in thread "ServerSocketService

### ISSUE THREAD

**Issue by Ido-Efrati** [google/caliper#312]
Running:
import com.google.caliper.runner.CaliperMain;

import java.util.HashSet;
import java.util.TreeSet;

public class Test  {
    // If you add a main function, you can run it from your IDE.
    public static void main(String[] args) throws Exception {
        CaliperMain.main(Test.class, args);

```
    // These are the command line arguments for Runner. You can add
            // "--trials", "10" to run each benchmark 10 times each.
}

private static final int SET_SIZE = 100000;

// Do the up-front allocation of things in the benchmark constructor,
// just like a unit test.
private final HashSet<Integer> hash = new HashSet<Integer>(100);
private final TreeSet<Integer> tree = new TreeSet<Integer>();

// Caliper looks for methods which start with "time"; gross, I know.
// The reps argument here is injected by Caliper, which uses it to factor
// out the cost of method invocation.
public void timeHashSetAdd(int reps) {
    // Be sure to add this outer loop.
    for (int i = 0; i < reps; i++) {
        // Then, in the inner loop, go ahead and do some meaningful work.
        // Here we're seeing how long it takes to add this many integers
        // to a set.
        for (int j = 0; j < SET_SIZE; j++) {
            hash.add(j);
        }
    }
}

// And now we've got a fight on our hands!
public void timeTreeSetAdd(int reps) {
    for (int i = 0; i < reps; i++) {
        for (int j = 0; j < 10000; j++) {
            tree.add(j);
        }
    }
}
```

}

Stack:
Experiment selection: 
  Benchmark Methods:   [timeHashSetAdd, timeTreeSetAdd]
  Instruments:   [allocation, runtime]
  User parameters:   {}
  Virtual machines:  [default]
  Selection type:    Full cartesian product

This selection yields 4 experiments.
ERROR: Trial failed to complete (its results will not be included in the run):
  The worker exited without producing data. It has likely crashed. Inspect C:\Users\User\AppData\Local\Temp\1434221187731-0\trial-2.log to see any worker output.
Exception in thread "ServerSocketService" java.lang.RuntimeException: java.net.SocketException: Connection reset
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:77)
    at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at com.google.caliper.bridge.OpenedSocket$2.read(OpenedSocket.java:193)
    at java.io.ObjectInputStream$PeekInputStream.read(Unknown Source)
    at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
    at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
    at java.io.ObjectInputStream.<init>(Unknown Source)
    at com.google.caliper.bridge.OpenedSocket.fromSocket(OpenedSocket.java:59)
    at com.google.caliper.runner.ServerSocketService.run(ServerSocketService.java:150)
    at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
    ... 2 more
java.lang.IllegalStateException: Expected the service to be RUNNING, but the service has FAILED
    at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:285)
    at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:229)
    at com.google.caliper.runner.TrialRunLoop.call(TrialRunLoop.java:83)
    at com.google.caliper.runner.TrialRunLoop.call(TrialRunLoop.java:47)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: The socket has been closed
    at com.google.caliper.runner.ServerSocketService.shutDown(ServerSocketService.java:210)
    at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:63)
    at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
    ... 1 more
ERROR: Trial failed to complete (its results will not be included in the run):
  The worker exited without producing data. It has likely crashed. Inspect C:\Users\User\AppData\Local\Temp\1434221187731-0\trial-1.log to see any worker output.
ERROR: Trial failed to complete (its results will not be included in the run):
  The worker exited without producing data. It has likely crashed. Inspect C:\Users\User\AppData\Local\Temp\1434221187731-0\trial-3.log to see any worker output.

An unexpected exception has been thrown by the caliper runner.
Please see https://sites.google.com/site/caliperusers/issues

**Comment by phishman3579** [comment]
What was in 'C:\Users\User\AppData\Local\Temp\1434221187731-0\trial-2.log'? That'll tell you the real problem.
