### ISSUE TITLE
guava version dependency seems to be wrong

### ISSUE THREAD

**Issue by benson-basis** [google/caliper#314]
1.0-beta-2  declares a maven dependency on guava 16.0.1, but using that leads to:

```
java.lang.IllegalStateException: Expected the service to be RUNNING, but the service has FAILED
    at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:334)
    at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:277)
    at com.google.caliper.runner.TrialRunLoop.call(TrialRunLoop.java:83)
    at com.google.caliper.runner.TrialRunLoop.call(TrialRunLoop.java:47)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
    at com.google.caliper.runner.StreamService.doStart(StreamService.java:130)
    at com.google.common.util.concurrent.AbstractService.startAsync(AbstractService.java:185)
    ... 7 more
```

Switching to 18.0 seems to fix it.

**Comment by cpovirk** [comment]
Fixed in master, though I don't think we've made a release with the fix: https://github.com/google/jimfs/issues/65
